# **3.2. NUMPY**

Numpy package is used for the scientific computation using ndarrays. The package can be used for performing various algebraic, numerical and logical operations on arrays. The package provides with shortcuts to deal with arrays which will be explored in detail here.

# **3.2.1. Installation**

The commands below can be used in the command prompt or Anaconda prompt based on the environment you are working on.

_"pip"_ can be used directly to install the numpy package in most of the environments

**_pip install numpy_**

_"conda install"_ on the otherhand is used in Anaconda and installs numpy package from Anaconda repository

**_conda install numpy_**

## **Importing a numpy package**

Importing any package in python can be done using the import command and can be called by a short name as shown below. Here we are importing <em>numpy</em> package and call it as <em>np</em>.


In [1]:
import numpy as np
print(np.__version__)

1.26.4


## **3.2.2. Numpy array**

Here we go through a basic example of initializing an array and displaying the most important attributes of the array. Most commonly used attributes associated with a Numpy array are as follows:

1. **array.shape** : This gives the shape of the array
2. **array.size** : This gives the total number of elements in an array
3. **array.ndim** : Number of axes in an array
4. **array.dtype**: Gives the datatype of elemts in the array

You can also define an array containing complex numbers.

The arrays can be printed as such using print command. Please look at the example shown below.

In [2]:
arr1 = np.array([1,2,3,4]) #intializing a simple arrray
print(arr1) # printing the 1-d array

arr2 = np.array([[1,2],[3,4]]) #initializing a 2 dimensional array
print(arr2) # printing the 2-d arrray

arr3 = np.array([[1.5, 3.2, 4.5, 3.8],
                 [1.3, 3.2, 5.6 , 4.2]]) #initializing an array of different data type
print(arr3)

print(arr1.shape, arr2.shape, arr3.shape) #printing the shape of the array
print(arr1.size, arr2.size, arr3.size) # printing the size of different arrays
print(arr1.ndim, arr2.ndim, arr3.ndim) #printing number of dimensions of the arrays
print(arr1.dtype, arr2.dtype, arr3.dtype) # displaying the data type of elements in the array

[1 2 3 4]
[[1 2]
 [3 4]]
[[1.5 3.2 4.5 3.8]
 [1.3 3.2 5.6 4.2]]
(4,) (2, 2) (2, 4)
4 4 8
1 2 2
int32 int32 float64


# **3.2.3. Creating different type of arrays**
1. **np.zeros** - Creates an array of zeros depending on the size we specify
2. **np.ones** - Creates an array of ones based on th eshape we specify
3. **np.empty** - creates an array that is intialized randomly. The data type of the elements is float64. The elements of the array can be random
4. **np.arange** - This function generates an array with sequence of numbers. This function also accepts arguments that are of floatpoint data type
5. **np.linspace** - _"linspace"_ function work similar to that of _"arange"_ but is generally used for creating graphs. This function can create lots of datapoints within a specified range.
    
_"arange"_ command uses step to generate the seqence whereas for _"linspace"_ the number of datapoints/elements needed within a range can be specified.

In [3]:
mat1 = np.zeros((5,4)) #using the function to create a zero matrix
print(mat1)
mat2 = np.ones((3,2)) #using the function to create a ones matrix
print(mat2)
mat3 = np.empty((2,2)) #using the function to create a random empty matrix
print(mat3)
mat4 = np.eye(3) #defining an 3x3 identity matrix
print(mat4)
mat5 = np.full((3,3),2) #creating a matrix containing a constant value
print(mat5)
mat6 = np.arange(1,50,3) #generating a sequence of data
print(mat6)
mat7 = np.linspace(1,50,3) #another way to generate sequence data
print(mat7)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[8.54516092e+194 1.27277580e+232]
 [1.32654817e-258 4.73224278e+164]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]
[ 1.  25.5 50. ]


# **3.2.4. Manipulating array shape**

The shape of the array can be changed using the following commands:
1. **array.ravel** : is used to flatten a matrix to array.
2. **array.reshape**: can modify the array or matrix to a desired shape. You can specify the dimenions of the new array.
3. **array.T**: can be used to obtain the transpose of a matrix
4. **array.resize**: works similar to _".reshape"_ and is used to modify the shape of the array or matrix. The main difference between the two is that _".reshape"_ gives a modified array and does not change the original array whereas _".resize"_ modifies the shape of original array itself.

In [4]:
import numpy as np
ar = np.array([[1,3,4,6,7],[1,5,6,5,4], #initializing an array
             [1,6,2,1,1],[2,4,5,8,3]])
print(ar)
print(ar.shape) #checking the shape of the array

ar1 = ar.reshape((5,4)) #modifying the shape of the array
print(ar1)
print(ar1.shape) #checking the shape of the modified array

ar2 = ar.ravel() #flattening a 2d array to 1d
print(ar2)
print(ar2.shape) #checking the shape of the modified array

ar3 = ar.T #taking the transpose of the array
print(ar3)
print(ar3.shape) #checking the shape of the transposed array

ar.resize((2,10)) #using resize to modify the original array
print(ar)
print(ar.shape) #checking the shape of the original array

[[1 3 4 6 7]
 [1 5 6 5 4]
 [1 6 2 1 1]
 [2 4 5 8 3]]
(4, 5)
[[1 3 4 6]
 [7 1 5 6]
 [5 4 1 6]
 [2 1 1 2]
 [4 5 8 3]]
(5, 4)
[1 3 4 6 7 1 5 6 5 4 1 6 2 1 1 2 4 5 8 3]
(20,)
[[1 1 1 2]
 [3 5 6 4]
 [4 6 2 5]
 [6 5 1 8]
 [7 4 1 3]]
(5, 4)
[[1 3 4 6 7 1 5 6 5 4]
 [1 6 2 1 1 2 4 5 8 3]]
(2, 10)


# **3.2.5. Stacking and splitting numpy arrays**

## **Stacking**
For stacking the following commands are used:

1. **np.hstack** : This performs columnwise stacking or horizontal stacking
2. **np.vstack** : This performs row-wise stacking or vertical stacking
3. **np.column_stack** : Stacks the 1D columns to 2D arrays and is equivalent to _np.hstack_ in the case of one dimensional stacking
4. **np.row_stack** : Stacks the rows and is equivalent to _np.vstack_

There are other functions such as **np.r_** and **np.c_** which allows adding sequence of numbers and range of numbers to the same axis.

Note that in the below code column_stack gives a different output compared to hstack when stacking arrays but vstack and row_stack work the same way.


In [5]:
import numpy as np
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,3,1])

ar_horizontal = np.hstack((array1,array2))    # using hstack
print(" Using hstack")
print(ar_horizontal, np.shape(ar_horizontal))
ar_vertical = np.vstack((array1,array2))      # using vstack
print( "using vstack")
print(ar_vertical, np.shape(ar_vertical))

ar_column = np.column_stack((array1,array2))  # using column_stack
print("Using column_stack : ")
print(ar_column, np.shape(ar_column))

ar_row = np.row_stack((array1, array2))       # using row_stack
print("Using row_stack:")
print(ar_row, np.shape(ar_row))

ar_r = np.r_[4:10,5:16, 0,1,2]               # using r_
print(ar_r)
ar_c = np.c_[4:10,5:11]                      # using c_
print(ar_c)

 Using hstack
[1 2 3 4 5 6 3 1] (8,)
using vstack
[[1 2 3 4]
 [5 6 3 1]] (2, 4)
Using column_stack : 
[[1 5]
 [2 6]
 [3 3]
 [4 1]] (4, 2)
Using row_stack:
[[1 2 3 4]
 [5 6 3 1]] (2, 4)
[ 4  5  6  7  8  9  5  6  7  8  9 10 11 12 13 14 15  0  1  2]
[[ 4  5]
 [ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]]



## **Splitting**
For splitting, the commonly used commands are **_hsplit_** and **_vsplit_** to do splitting along the horizontal axis and vertical axis respectively. Alternatively, **_array_split_** can be used for doing the splitting similarly by specifying the axis.

In [6]:
import numpy as np
print("\n using hsplit")
print(np.hsplit(ar_row,2))                  # using hsplit for splitting along the columns
print("\n using vsplit")
print(np.vsplit(ar_row,2))                  # using vsplit for splitting along the rows

print("\n using array_split")

print("\n along column similar to hsplit")
print(np.array_split(ar_row,2, axis = 1))   # using array_split command
print("\n along row similar to vsplit")
print(np.array_split(ar_row,2, axis = 0))


 using hsplit
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [3, 1]])]

 using vsplit
[array([[1, 2, 3, 4]]), array([[5, 6, 3, 1]])]

 using array_split

 along column similar to hsplit
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [3, 1]])]

 along row similar to vsplit
[array([[1, 2, 3, 4]]), array([[5, 6, 3, 1]])]


# **3.2.6  Indexing and slicing**

Indexing helps us in accessing elements of an array and Slicing can help us get the data in a specific range. For slicing we make use of colon _:_ operation to select a certain range.

## **Example 3.2.2**

This example shows how the indexing can be done for one-dimensional and two-dimensional arrays. Similarly, we will also explore of different kinds of slicing techniques that can be implemented using the numpy arrays. In addition to this, we will also be using some of the previously discussed commands in this exampl


# **Indexing**

In [7]:
import numpy as np
array1 = np.array([1,2,3,4])                                       # initializing a 1D numpy array
print(array1)
print('printing 1st & 4th element: \n', array1[0], array1[3])      # printing the first and the fourth element
print('sum of the 2nd and 3rd element: \n', array1[1]+array1[2])   # printing the sum of the 2nd & 3rd element
array2 = np.array([2, 3, 4, 6])                                    # initializing another one dimensional array
print(array2)
array3 = np.vstack((array1,array2))                                # doing a vertical stack to create a 2D array
print('Displaying the array:  \n', array3, array3.shape)           # printing the 2D array and displaying its shape

print('2nd row, 4th element: ', array3[1,3])                       # printing the array element at 2nd row and 4th column
print('1st row, 3rd element: ', array3[0,2])                       # printing the array element at 1st row and 3rd column

print('last element of 1st row: ', array3[0,-1])                   # example of negative indexing to print the last element of the 1st row


[1 2 3 4]
printing 1st & 4th element: 
 1 4
sum of the 2nd and 3rd element: 
 5
[2 3 4 6]
Displaying the array:  
 [[1 2 3 4]
 [2 3 4 6]] (2, 4)
2nd row, 4th element:  6
1st row, 3rd element:  3
last element of 1st row:  4


# **Slicing**
Note that when specifying the range **_array1[start:end]_**, the element at the starting index is always included and the element at the end index is not included.

In [8]:
import numpy as np
array4 = np.column_stack((array1,array2))                     # Using column_stack to stack the two 1d arrays to obtain another 2D array
print(array4)
print('Printing array and its shape: \n', array4, array4.shape) # Printing the new 2D array and the shape of the array

print('Slicing 1D array: \n',array1[1:4], array1[1:])         # Printing the 2nd element to 4th element using two ways

print('Negative slicing 1D array: \n',array1[:-1])            # Printing all elements of array except the last one using negative slicing

print('Slicing a 2D array along row: \n',array4[1:4,:])       # Accessing rows 2 to 4 in the 2D array using slicing

print('Slicing a 2D array along column: \n',array4[:,0:1])    # Accessing column 1 in the 2D array using slicing

print('Negative slicing 2D: \n', array4[:-1,:])               # printing all the rows except the last one
print('Slicing along both row and column: \n', array4[0:2,:-1]) # printing only the first column 1st and second elements

[[1 2]
 [2 3]
 [3 4]
 [4 6]]
Printing array and its shape: 
 [[1 2]
 [2 3]
 [3 4]
 [4 6]] (4, 2)
Slicing 1D array: 
 [2 3 4] [2 3 4]
Negative slicing 1D array: 
 [1 2 3]
Slicing a 2D array along row: 
 [[2 3]
 [3 4]
 [4 6]]
Slicing a 2D array along column: 
 [[1]
 [2]
 [3]
 [4]]
Negative slicing 2D: 
 [[1 2]
 [2 3]
 [3 4]]
Slicing along both row and column: 
 [[1]
 [2]]


# **3.2.7. Arithmetic operations and mathematical functions**


## **Arithmetic operations:**

The basic operations such as addition, subtraction, multiplication and division are dealt here. The following commands can be used for performing different array based operations:

1. **np.add(a,b)**: performs elementwise addition of the two arrays
2. **np.subtract(a,b)**: performs elementwise subtraction of the two arrays
3. **np.multiply(a,b)**: does elemntwise multiplication of the two arrays
4. **np.divide(a,b)**: Divides elements of array _a_ with elements of array _b_
5. **np.remainder(a,b)**: Computes the remainder between array _a_ and array _b_
6. **np.reciprocal(a)**: Calculates _1/a_ for each element in an array. Note that here the division is integer division. Therefore, for _a_>1 the reciprocal is always returned as 0.
7. **np.sqrt(a)** :  Computes the square root of the elements in array _a_
8. **np.power(a,b)**: Computes the power of elements of _a_ to elements of _b_

On arrays with complex numbers we can use numpy to perform different operations such as follows:

1. **np.complex()**: can be used to create a complex number from to inputs
2. **np.real()**   : obtains the real part of elements of an array
3. **np.imag()**   : Obtains the imaginary part of the elements of an array
4. **np.conj()**   : Computes the conjugate of the array elements
5. **np.abs()**    : Used to obtain the absolute value of the array elements
6. **np.angle()**  : use to get the angle of the complex elements

In [9]:
import numpy as np

a = np.array([1,2,3,4])   # creating two arrays a and b
b = np.array([4,5,1,2])
print(a,b)
add_ab = np.add(a,b)      # using the numpy addition operation
print("after addition")
print(add_ab)

c = b*0.1                 # creating another array by multipling "b" with 0.1

rec_b = np.reciprocal(b)  # computing the reciprocal of array b
rec_c = np.reciprocal(c)  # computing the reciprocal of new array c
print("using reciprocal on b and b*0.1")
print(rec_b, rec_c)

pow_ab = np.power(a,b)   # computing the power of a to b
print("taking the power of a & b")
print(pow_ab)

sqrt_a = np.sqrt(a)       # computing the square root of a
print("taking the square root of a")
print(sqrt_a)

zip_obj = zip(a, b)      # lets zip the two arrays to get a complex data
comp = []                # create an empty list

for a,b in zip_obj:      # use for loop to obtain the elements of arrays a & b
    c = complex(a,b)  # compute a+jb using np.complex function (#Note that np.complex was changed to complex due to update in Numpy package version.)
    comp.append(c)       # append these to the empty list
print("complex array:")
print(comp)

print("real part of the array")
print(np.real(comp))     # getting real part of the complex array


[1 2 3 4] [4 5 1 2]
after addition
[5 7 4 6]
using reciprocal on b and b*0.1
[0 0 1 0] [ 2.5  2.  10.   5. ]
taking the power of a & b
[ 1 32  3 16]
taking the square root of a
[1.         1.41421356 1.73205081 2.        ]
complex array:
[(1+4j), (2+5j), (3+1j), (4+2j)]
real part of the array
[1. 2. 3. 4.]


## **Mathematical functions:**

1. __Trigonometric functions__:

   a) _np.sin_, _np.cos_, _np.tan_ are used for computing element wise trigonometric operation.<br>
   b) _np.arcsin_, _np.arccos__np.arctan_ are used for performing inverse trigonometric operations.<br>
   c) _np.degrees_, _np.radians_, _np.deg2rad_, _np.rad2deg_ are used for converting the angles from radians to degrees and vice versa.
   
   
2. __Hyperbolic functions__:

   a) _np.sinh_, _np.cosh_, _np.tanh_ are used for computing element wise hyerbolic operation.<br>
   b) _np.arcsinh_, _np.arccosh__np.arctanh_ are used for performing inverse hyperbolic operations.<br>
   
3. __Rounding functions__:

   a) _np.around_ : even rounding. Can also specify the decimal place to be rounded to. <br>
   b) _np.round_: Round an array to a given number of decimal places.<br>
   c) _np.floor_ : get the floor of input, round to the minimum value.<br>
   d) _np.ceil_ :get the ceiling of input, round to the maximum value.<br>

In [10]:
import numpy as np
a = np.array([30,45,60,90])   # creating an array of degrees
print(a)
print("\n sin(a) = ")
print(np.sin(np.radians(a))) # convert to radians and print the sine of it
print("\n tanh(a) = ")
print(np.tanh(np.radians(a))) # convert to radians and print the tanh of it


b = np.array([0.35066070245,2.67822320434]) # creating an array of decimal numbers
print(b)

print("\n round of decimal to fourth decimal place:")
print(np.around(b, 4)) #print the round of decimal values to the 4th decimal place

print("\n using floor")
print(np.floor(b))   # use floor command
print("\n using ceil")
print(np.ceil(b))    # use ceil command

[30 45 60 90]

 sin(a) = 
[0.5        0.70710678 0.8660254  1.        ]

 tanh(a) = 
[0.48047278 0.6557942  0.78071444 0.91715234]
[0.3506607 2.6782232]

 round of decimal to fourth decimal place:
[0.3507 2.6782]

 using floor
[0. 2.]

 using ceil
[1. 3.]


## **Example 3.2.3: Neural network with Numpy and classes**

Again we are going to revisit example 1.6.2 from Chapter 1. In example 2.1.3, we define the two datasets as a class. Similarly, we are going to construct a class named _'NeuralNetwork'_ for defining the structure of the Multilayer perceptron. In both these cases, we are using basic Numpy to construct the code. Through these examples you can learn various functionalities associated with the Numpy package.


In [11]:
import numpy as np

class NeuralNetwork:
    def __init__(self,D,activation,output):
        # Puts the neural network as a dictionary
        self.NN={"weights":[],"bias":[],"dimensions":[],"activation":[]}
        # D: np. array with the number of nodes in each layer, including input and output
        self.D=D
        # activations: Hidden node activations--'ReLU', 'logistic', 'maxOut'
        self.activation=activation
        # output: Output layer activations--'linear', 'logistic', 'softMax
        self.output=output

    def layer(self,Di,Do):
        # Create some structures for the weights and the biases
        # Here we assume that the input is a vector, so the weights are a 2D array
        W=np.random.randn(Di,Do)/np.sqrt(Di) #This is simply the Xavier initialization
        b=np.random.randn(1,Do)/np.sqrt(Di)
        return W,b

    def network_structure(self):
        for i in range(self.D.size-1):
            W,b= self.layer(self.D[i],self.D[i+1])
            self.NN["weights"].append(W)
            self.NN["bias"].append(b)
            self.NN["dimensions"]=self.D
            if i<self.D.size-2:
                self.NN["activation"].append(self.activation)
            else:
                self.NN["activation"].append(self.output)
        MLP=self.NN
        return MLP
output_activation="logistic" #define the activation.
hidden_activation="relu" #define the activation.
D=np.array([2,100,1]) #define the number of nodes in each layer.
#define the object and the instance variables.
NN1=NeuralNetwork(D,hidden_activation,output_activation)
#define the method corresponding to network structure.
neural_net=NN1.network_structure()